### ISSUE TITLE
提示在_header.pug的theme.menu出现了问题，如下。请问我该怎么解决？

### ISSUE THREAD

**Issue by whitealco** [XadillaX/hexo-xnew#1]
ERROR
TypeError: E:\blog\hexo\themes\xnew\layout\_header.pug:9
    7| nav
    8|   ul
  > 9|     each url, label in theme.menu
    10|       li
    11|         a(href= url, alt= label, title= label)= label
    12|

Cannot read properties of undefined (reading 'length')
    at eval (eval at wrap (E:\blog\hexo\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:117:32)
    at eval (eval at wrap (E:\blog\hexo\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:140:4)
    at template (eval at wrap (E:\blog\hexo\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:915:7)
    at _View._compiled (E:\blog\hexo\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (E:\blog\hexo\node_modules\hexo\lib\theme\view.js:39:17)
    at E:\blog\hexo\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (E:\blog\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at E:\blog\hexo\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (E:\blog\hexo\node_modules\hexo\lib\hexo\router.js:47:5)
    at Readable.read (node:internal/streams/readable:496:12)
    at resume_ (node:internal/streams/readable:999:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
ERROR
TypeError: E:\blog\hexo\themes\xnew\layout\_header.pug:9
    7| nav
    8|   ul
  > 9|     each url, label in theme.menu
    10|       li
    11|         a(href= url, alt= label, title= label)= label
    12|

Cannot read properties of undefined (reading 'length')
    at eval (eval at wrap (E:\blog\hexo\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:117:32)
    at eval (eval at wrap (E:\blog\hexo\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:140:4)
    at template (eval at wrap (E:\blog\hexo\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:915:7)
    at _View._compiled (E:\blog\hexo\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (E:\blog\hexo\node_modules\hexo\lib\theme\view.js:39:17)
    at E:\blog\hexo\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (E:\blog\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at E:\blog\hexo\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (E:\blog\hexo\node_modules\hexo\lib\hexo\router.js:47:5)
    at Readable.read (node:internal/streams/readable:496:12)
    at resume_ (node:internal/streams/readable:999:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
ERROR
TypeError: E:\blog\hexo\themes\xnew\layout\_header.pug:9
    7| nav
    8|   ul
  > 9|     each url, label in theme.menu
    10|       li
    11|         a(href= url, alt= label, title= label)= label
    12|

Cannot read properties of undefined (reading 'length')
    at eval (eval at wrap (E:\blog\hexo\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:117:32)
    at eval (eval at wrap (E:\blog\hexo\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:140:4)
    at template (eval at wrap (E:\blog\hexo\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:915:7)
    at _View._compiled (E:\blog\hexo\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (E:\blog\hexo\node_modules\hexo\lib\theme\view.js:39:17)
    at E:\blog\hexo\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (E:\blog\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at E:\blog\hexo\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (E:\blog\hexo\node_modules\hexo\lib\hexo\router.js:47:5)
    at Readable.read (node:internal/streams/readable:496:12)
    at resume_ (node:internal/streams/readable:999:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
ERROR
TypeError: E:\blog\hexo\themes\xnew\layout\_header.pug:9
    7| nav
    8|   ul
  > 9|     each url, label in theme.menu
    10|       li
    11|         a(href= url, alt= label, title= label)= label
    12|

Cannot read properties of undefined (reading 'length')
    at eval (eval at wrap (E:\blog\hexo\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:117:32)
    at eval (eval at wrap (E:\blog\hexo\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:140:4)
    at template (eval at wrap (E:\blog\hexo\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:915:7)
    at _View._compiled (E:\blog\hexo\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (E:\blog\hexo\node_modules\hexo\lib\theme\view.js:39:17)
    at E:\blog\hexo\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (E:\blog\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at E:\blog\hexo\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (E:\blog\hexo\node_modules\hexo\lib\hexo\router.js:47:5)
    at Readable.read (node:internal/streams/readable:496:12)
    at resume_ (node:internal/streams/readable:999:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
ERROR
TypeError: E:\blog\hexo\themes\xnew\layout\_header.pug:9
    7| nav
    8|   ul
  > 9|     each url, label in theme.menu
    10|       li
    11|         a(href= url, alt= label, title= label)= label
    12|

Cannot read properties of undefined (reading 'length')
    at eval (eval at wrap (E:\blog\hexo\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:117:32)
    at eval (eval at wrap (E:\blog\hexo\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:140:4)
    at template (eval at wrap (E:\blog\hexo\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:915:7)
    at _View._compiled (E:\blog\hexo\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (E:\blog\hexo\node_modules\hexo\lib\theme\view.js:39:17)
    at E:\blog\hexo\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (E:\blog\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at E:\blog\hexo\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (E:\blog\hexo\node_modules\hexo\lib\hexo\router.js:47:5)
    at Readable.read (node:internal/streams/readable:496:12)
    at resume_ (node:internal/streams/readable:999:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
ERROR
TypeError: E:\blog\hexo\themes\xnew\layout\_header.pug:9
    7| nav
    8|   ul
  > 9|     each url, label in theme.menu
    10|       li
    11|         a(href= url, alt= label, title= label)= label
    12|

Cannot read properties of undefined (reading 'length')
    at eval (eval at wrap (E:\blog\hexo\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:117:32)
    at eval (eval at wrap (E:\blog\hexo\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:140:4)
    at template (eval at wrap (E:\blog\hexo\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:915:7)
    at _View._compiled (E:\blog\hexo\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (E:\blog\hexo\node_modules\hexo\lib\theme\view.js:39:17)
    at E:\blog\hexo\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (E:\blog\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at E:\blog\hexo\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (E:\blog\hexo\node_modules\hexo\lib\hexo\router.js:47:5)
    at Readable.read (node:internal/streams/readable:496:12)
    at resume_ (node:internal/streams/readable:999:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
ERROR Asset render failed: styles/basic.css
Error: E:/blog/hexo/node_modules/stylus/lib/functions/index.styl:133:3
   129|
   130| // lighten by the given amount
   131|
   132| lighten(color, amount)
   133|   adjust(color, 'lightness', amount)
----------^
   134|
   135| // decrease opacity by amount
   136|

TypeError: expected rgba or hsla, but got ident:$body-color
    at "a" (E:\blog\hexo\themes\xnew\source\styles\basic.styl:20:13)
    at "article.full" (E:\blog\hexo\themes\xnew\source\styles\basic.styl:18:2)

    at exports.assertColor (E:\blog\hexo\node_modules\stylus\lib\utils.js:255:13)
    at Evaluator.adjust (E:\blog\hexo\node_modules\stylus\lib\functions\adjust.js:14:9)
    at Evaluator.invokeBuiltin (E:\blog\hexo\node_modules\stylus\lib\visitor\evaluator.js:1054:30)
    at Evaluator.visitCall (E:\blog\hexo\node_modules\stylus\lib\visitor\evaluator.js:516:16)
    at Visitor.visit (E:\blog\hexo\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (E:\blog\hexo\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.visitExpression (E:\blog\hexo\node_modules\stylus\lib\visitor\evaluator.js:644:26)
    at Visitor.visit (E:\blog\hexo\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (E:\blog\hexo\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.eval (E:\blog\hexo\node_modules\stylus\lib\visitor\evaluator.js:1238:23)
    at Evaluator.invoke (E:\blog\hexo\node_modules\stylus\lib\visitor\evaluator.js:1083:16)
    at Evaluator.invokeFunction (E:\blog\hexo\node_modules\stylus\lib\visitor\evaluator.js:1012:15)
    at Evaluator.visitCall (E:\blog\hexo\node_modules\stylus\lib\visitor\evaluator.js:522:16)
    at Visitor.visit (E:\blog\hexo\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (E:\blog\hexo\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.visitExpression (E:\blog\hexo\node_modules\stylus\lib\visitor\evaluator.js:644:26)
    at Visitor.visit (E:\blog\hexo\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (E:\blog\hexo\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.visitProperty (E:\blog\hexo\node_modules\stylus\lib\visitor\evaluator.js:687:22)
    at Visitor.visit (E:\blog\hexo\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (E:\blog\hexo\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.visitBlock (E:\blog\hexo\node_modules\stylus\lib\visitor\evaluator.js:720:39)
ERROR Asset render failed: styles/main.css
Error: E:/blog/hexo/node_modules/stylus/lib/functions/index.styl:128:3
   124|
   125| // darken by the given amount
   126|
   127| darken(color, amount)
   128|   adjust(color, 'lightness', - amount)
----------^
   129|
   130| // lighten by the given amount
   131|

TypeError: expected rgba or hsla, but got ident:$background-color
    at "&:after" (E:\blog\hexo\themes\xnew\source\styles\main.styl:56:5)
    at "article.item" (E:\blog\hexo\themes\xnew\source\styles\main.styl:39:43)
    at "main" (E:\blog\hexo\themes\xnew\source\styles\main.styl:95:23)

    at exports.assertColor (E:\blog\hexo\node_modules\stylus\lib\utils.js:255:13)
    at Evaluator.adjust (E:\blog\hexo\node_modules\stylus\lib\functions\adjust.js:14:9)
    at Evaluator.invokeBuiltin (E:\blog\hexo\node_modules\stylus\lib\visitor\evaluator.js:1054:30)
    at Evaluator.visitCall (E:\blog\hexo\node_modules\stylus\lib\visitor\evaluator.js:516:16)
    at Visitor.visit (E:\blog\hexo\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (E:\blog\hexo\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.visitExpression (E:\blog\hexo\node_modules\stylus\lib\visitor\evaluator.js:644:26)
    at Visitor.visit (E:\blog\hexo\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (E:\blog\hexo\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.eval (E:\blog\hexo\node_modules\stylus\lib\visitor\evaluator.js:1238:23)
    at Evaluator.invoke (E:\blog\hexo\node_modules\stylus\lib\visitor\evaluator.js:1083:16)
    at Evaluator.invokeFunction (E:\blog\hexo\node_modules\stylus\lib\visitor\evaluator.js:1012:15)
    at Evaluator.visitCall (E:\blog\hexo\node_modules\stylus\lib\visitor\evaluator.js:522:16)
    at Visitor.visit (E:\blog\hexo\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (E:\blog\hexo\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.visitExpression (E:\blog\hexo\node_modules\stylus\lib\visitor\evaluator.js:644:26)
    at Visitor.visit (E:\blog\hexo\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (E:\blog\hexo\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.visitProperty (E:\blog\hexo\node_modules\stylus\lib\visitor\evaluator.js:687:22)
    at Visitor.visit (E:\blog\hexo\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (E:\blog\hexo\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.visitBlock (E:\blog\hexo\node_modules\stylus\lib\visitor\evaluator.js:720:39)

**Comment by XadillaX** [comment]
你写了 _config.yml 吗？

**Comment by whitealco** [comment]
请问是写 _config的哪些内容呢？非常抱歉，我有点不懂。

**Comment by whitealco** [comment]
请问是把主题文件夹config.sample里的内容复制到根目录下config里吗？如果是这样的话，它依旧是报了那个错误
ERROR
TypeError: E:\blog\hexo\themes\xnew\layout\_header.pug:9
    7| nav
    8|   ul
  > 9|     each url, label in theme.menu
    10|       li
    11|         a(href= url, alt= label, title= label)= label
    12|

Cannot read properties of undefined (reading 'length')
    at eval (eval at wrap (E:\blog\hexo\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:117:32)
    at eval (eval at wrap (E:\blog\hexo\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:140:4)
    at template (eval at wrap (E:\blog\hexo\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:915:7)
    at _View._compiled (E:\blog\hexo\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (E:\blog\hexo\node_modules\hexo\lib\theme\view.js:39:17)
    at E:\blog\hexo\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (E:\blog\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at E:\blog\hexo\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (E:\blog\hexo\node_modules\hexo\lib\hexo\router.js:47:5)
    at Readable.read (node:internal/streams/readable:496:12)
    at resume_ (node:internal/streams/readable:999:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

**Comment by XadillaX** [comment]
应该是复制一份到你的主题目录

**Comment by whitealco** [comment]
哇，可以了，感谢，非常感谢。我之前一直搞错了，我一直以为放在themes文件里也是可以的，现在才发现是我一直以来都理解错了（哭笑不得）。真的非常感谢。
